### PR TITLE
Add feature to support ToBottomMargin, ToTopMargin, ToLeftMargin, ToRightMargin

### PR DESCRIPTION
**Pull request by sungcheng**
@gshackles, thoughts?

### CODE REVIEW

**Comment by munkii** [comment]
This gets my vote FWIW :-) I am also starting to use the Margin LayoutAttributes. Also ReadableContentGuide and TopLayoutGuide as the SecondItem. Currently the SecondItem needs to be a UIView in FluentLayout

**Comment by gshackles** [comment]
You've got east and west mixed up here 😄 

image

**Comment by sungcheng** [comment]
😁  that would explain why I get lost all the time.  Ok will fix.

**Comment by sungolo** [comment]
@gshackles, PTAL.

simulator screen shot may 8 2016 6 19 39 pm

**Pull request merged**
