### PR TITLE
Adds Mac support

### PR DESCRIPTION
**Pull request by michaelstonis**
Adds in support for fluent layout constraints that work on the mac

### CODE REVIEW

**Comment by slodge** [comment]
ooooooh :+1: 

I like the `_nativeLayoutConstraint` change :) I wonder if that can be used within an extension method to provide animation....

I like the shared project too... :)

Can't merge this right now - as I'm on a PeeCee and as I don't quite have a xam.mac license.... but soon... (unless someone beats me to it)

**Comment by michaelstonis** [comment]
I forgot that I had checked this in as well. This is _specifically_ for animations. You would still need to capture can instance of the fluent layout object, but from there, you can update a few properties (constant, active, priority) and have it animate. I updated the sample MyViewController to show off some of those animations.

**Comment by michaelstonis** [comment]
Any thoughts or feedback on this?

**Comment by gshackles** [comment]
Closing this since the branch/PR has gotten stale and has conflicts, but please do open a new PR if there are still changes you'd like to contribute!

**Pull request closed without merging**
