### PR TITLE
.NET 6

### PR DESCRIPTION
**Pull request by evgenyvalavin**
Updated the main Cirriouse.Fluentlayouts.Touch project.
Didn't spend time to update to .NET 6 the Demo in the solution because the demo is too old and I think it requires too much effort at the moment

### CODE REVIEW

**Comment by vallgrenerik** [comment]
Nice work @evgenyvalavin ! 
@gshackles did you see this?

**Review by gshackles — COMMENTED** [review]
Sorry I had in fact missed this, thanks for the ping! I don't spend much time in the Xamarin world of late so haven't been on top of this library lately. Thanks also for putting in the effort to make these changes! 

@Cheesebaron did you want to take a pass here in reviewing and we can figure out the right path forward on these changes?

**Comment by Cheesebaron** [comment]
@gshackles I will have a look at this yes 👍

**Comment by evgenyvalavin** [comment]
I've been in Xamarin development for more than three years. Developing an iOS project is not an easy one. At least a developer has to write UI by using UiKit and C#. I have my own thoughts on how to ease iOS development process. I'd share the thoughts by open sourcing a private project.

@gshackles what do you think if I include FluentLayout's source code in the project I want to open source and publish it as a NuGet package? The idea for the package name is "iOS.Essentials". To be honest I already have such package but in a private NuGet feed.
There may be no need to figure out a path on releasing Cirrious.FluentLayout for net6

**Comment by Cheesebaron** [comment]
As per the license (see [LICENSE](https://github.com/FluentLayout/Cirrious.FluentLayout/blob/main/LICENSE)) of this project, you are allowed to do so. However, you must provide proper attribution of the copyright and you must include the original LICENSE in your project.

**Pull request merged**
